version: '3.8'
services:
  db:
    image: postgres:15
    container_name: urlshortener-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5399:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: