version: '3.8'
services:
  db:
    image: postgres:15
    container_name: urlshortener-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5399:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortener
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  db_data: