spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/url_shortener
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8080}