spring:
  datasource:
    url: jdbc:postgresql://localhost:5399/url_shortener
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8080